name = "docvault"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
# DATABASE_URL = "..."
# DIRECT_URL = "..."

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "362597e281f6486ea464b64c1e318b05"

[site]
bucket = ".vercel/output/static"
